openapi: 3.0.0
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
servers: []
tags:
  - name: cats
    description: ''
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
components:
  schemas: {}
